export const menuLists = [
    {
        route:'/dashboard',
        text:"Dashboard",
        activeImg:"dashboard-white.png",
        img:"dashboard.png"
    },
    {
        route:"/advertising",
        text:"Create Advertising",
        activeImg:"ad-white.png",
        img:"ad.png"
    },
    {
        route:"/user",
        text:"User",
        activeImg:"user-white.png",
        img:"user.png"
    },
    {
        route:"/category",
        text:"Category",
        activeImg:"category-white.png",
        img:"category.png"
    },
    {
        route:"/products",
        text:"Products",
        activeImg:"product-white.png",
        img:"product.png"
    },
    {
        route:"/order",
        text:"Order",
        activeImg:"order-white.png",
        img:"orders.png"
    },
    {
        route:"/logout",
        text:"Logout",
         activeImg:"logout-white.png",
        img:"logout.png"
    }
]